name: dart_enum_to_string_check
description: A plugin for Dart Analyzer for checking enum.toString() usages.
version: 0.8.0
homepage: https://github.com/fartem/dart-enum-to-string-check

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  analyzer: ^1.7.0
  analyzer_plugin: ^0.6.0
  glob: ^2.0.1
  path: ^1.8.0
  yaml: ^3.1.0
  file: ^6.0.0

dev_dependencies:
  test: ^1.16.8
