name: dart_enum_to_string_check
description: A plugin for Dart Analyzer for checking enum.toString() usages.
version: 0.7.0
homepage: https://github.com/fartem/dart-enum-to-string-check

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  analyzer: ^0.41.0
  analyzer_plugin: ^0.4.0
  glob: ^1.2.0
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  test: ^1.16.5
