name: dart_enum_to_string_check
description: A plugin for Dart Analyzer for checking enum.toString() usages.
author: fartem
version: 0.6.1
homepage: https://github.com/fartem/dart-enum-to-string-check

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  analyzer: ^0.39.3
  analyzer_plugin: '>=0.2.1 <0.4.0'
  glob: ^1.1.7
  path: ^1.6.2
  yaml: ^2.2.1

dev_dependencies:
  test: ^1.15.7
