name: dart_enum_to_string_check
description: A plugin for Dart Analyzer for checking enum.toString() usages.
version: 0.5.0
homepage: https://github.com/wrike/dart-code-metrics

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  analyzer: ^0.39.3
  analyzer_plugin: '>=0.2.1 <0.4.0'
  glob: ^1.1.7
  path: ^1.6.2

dev_dependencies:
  effective_dart: ^1.2.0
